name: Latest blog post workflow
on:
    push:
        branches:
            - master
    schedule:
        - cron: '0 * * * *'
jobs: 
    update-readme-with-blog: 
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v2
            - uses: gautamkrishnar/blog-post-workflow@master
              with: 
                max_post_count: "4"
                feed_list: "https://www.nishitpatel.tech/feed.xml"
    update-readme-with-gitlab:
        name: Update this repo's README with latest activity from gitlab
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: gautamkrishnar/blog-post-workflow@master
            with:
              comment_tag_name: "GITLAB"
              committer_username: "Nishit Patel"
              committer_email: "nishitlimbani130@gmail.com"
              commit_message: "Updated readme with the latest gitlab data"
              feed_list: "https://gitlab.gnome.org/nis130.atom"
